# login with facebook environment in docker
version: '3.3'

services:
  app:
    image: nginx:latest
    ports:
      - "80:80"
      - "3000:443"
    restart: always
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/ssl:/etc/ssl
      - ./app:/var/www/html
    container_name: auth_oauth2_nginx
    # command: /bin/sh -c "mkdir /var/www/html/data/logs && touch /var/www/html/data/logs/access_log.txt && chmod 755 /var/www/html/data/logs && chmod 777 /var/www/html/data/logs/access_log.txt"
    links:
      - php
      - mongodb
      - composer
    depends_on:
      - php
      - composer
      - mongodb

  php:
    build: ./php
    links:
      - mongodb
    restart: always
    container_name: auth_oauth2_php
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./app:/var/www/html

  composer:
    image: composer:latest
    links:
      - php
    container_name: auth_oauth2_composer
    volumes:
      - ./app:/app
    command: install --ignore-platform-reqs
    restart: 'no'

  mongodb:
    image: mongo:latest
    container_name: auth_oauth2_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
    restart: always
    volumes:
      - ./data/db/mongo:/data/db
    command: mongod --smallfiles
    ports:
      - 27017:27017
